### ISSUE TITLE
Paralax

### ISSUE THREAD

**Issue by imedacf** [imedacf/BlackCard#17]
1. წერტილები უფრო პატარა
2. ხაზები უფრო სქელი
3. ჟორჟიკას ეფექტი პარალაქსზე
4. რადიუსი პატარა
5. გრადიენტი ვცადოთ რამე

**Comment by Gogola** [comment]
მოკლედ, რადიუსი ნორმალურია, წერტილები დავაპატარავე და ხაზებიც გავასქელე ცოტა. გრადიენტია დარჩენილი რომელიც არ ვიცი და @imedacf ცადე შენ.
