### ISSUE TITLE
gift->point

### ISSUE THREAD

**Issue by imedacf** [imedacf/BlackCard#3]
```gifts``` ცხრილში დასამატებელია ```point```.

**Comment by nikajorjika** [comment]
gifts price aqvs da point ragat unda

**Comment by Gogola** [comment]
@nikajorjika me mgoni erti da igiveze idzaxi, prices rols asrulebs pointi, anu 1300 qulas ro sheagrovebs momxmarebeli mere yidulobs sachukars
